# Generated by Django 5.2.8 on 2025-12-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenities/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_text', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='places/covers/')),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='places.category')),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('license_status', models.CharField(default='Pending', max_length=50)),
                ('amenities', models.ManyToManyField(blank=True, related_name='establishments', to='places.amenity')),
            ],
            options={
                'abstract': False,
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('landmark_type', models.CharField(blank=True, max_length=100)),
                ('road_condition', models.CharField(blank=True, max_length=200)),
                ('safety_instructions', models.TextField(blank=True)),
                ('best_visit_time', models.CharField(blank=True, max_length=100)),
                ('climate_description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('service_type', models.CharField(max_length=100)),
                ('is_24_hours', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('places.place',),
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='places.category'),
        ),
        migrations.CreateModel(
            name='PlaceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.ImageField(upload_to='places/media/')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('is_cover', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='establishments/units/')),
                ('description', models.TextField(blank=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='places.establishment')),
            ],
        ),
    ]
