# Generated by Django 4.2.27 on 2025-12-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this place should be treated as active.'),
        ),
    ]
