# Generated by Django 4.2.27 on 2025-12-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='road_condition',
        ),
        migrations.AddField(
            model_name='place',
            name='classification',
            field=models.CharField(choices=[('general', 'General'), ('family', 'Family Only')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='road_condition',
            field=models.CharField(choices=[('paved', 'Paved'), ('offroad', 'Off-road (4x4)')], default='paved', max_length=20),
        ),
    ]
