# Generated by Django 4.2.27 on 2025-12-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_landmark_road_condition_place_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='pending_updates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
