# Generated by Django 4.2.27 on 2025-12-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_establishment_pending_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='commercial_registry_image',
            field=models.ImageField(blank=True, null=True, upload_to='establishments/registries/'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='is_open_status',
            field=models.BooleanField(default=True, help_text='Indicates if the establishment is currently open for business.'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='establishments/licenses/'),
        ),
    ]
