# Generated by Django 4.2.27 on 2025-12-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_establishment_commercial_registry_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemedia',
            name='media_url',
            field=models.FileField(upload_to='places/media/'),
        ),
    ]
