# Generated by Django 4.2.27 on 2025-12-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_placemedia_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='update_note',
            field=models.TextField(blank=True, help_text='Admin notes for the partner regarding the update'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='update_status',
            field=models.CharField(choices=[('none', 'No Updates'), ('pending', 'Pending Review'), ('needs_info', 'Needs More Info')], default='none', max_length=20),
        ),
    ]
