# Generated by Django 4.2.27 on 2025-12-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_establishment_update_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='directorate',
            field=models.CharField(choices=[('AL_DHIHAR', 'الظهار'), ('AL_MASHANNAH', 'المشنة'), ('JIBLA', 'جبلة'), ('AL_SADDAH', 'السدة'), ('BAADAN', 'بعدان'), ('AL_SABRA', 'السبرة'), ('AL_UDAYN', 'العدين'), ('HAZM_AL_UDAYN', 'حزم العدين'), ('FAR_AL_UDAYN', 'فرع العدين'), ('HUBISH', 'حبيش'), ('AL_MAKHADIR', 'المخادر'), ('AL_QAFR', 'القفر'), ('YARIM', 'يريم'), ('AL_RADMA', 'الرضمة'), ('AL_NANIYANI', 'السياني'), ('ZI_ALSUFAL', 'ذي السفال'), ('AL_MANDAR', 'المندر')], default='AL_DHIHAR', max_length=50, verbose_name='المديرية'),
        ),
    ]
