# Generated by Django 4.2.27 on 2025-12-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_place_directorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='موثق'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الترخيص'),
        ),
    ]
