# Generated by Django 4.2.27 on 2025-12-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_establishment_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='معلق'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='suspension_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التعليق'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='suspension_reason',
            field=models.TextField(blank=True, verbose_name='سبب التعليق'),
        ),
    ]
