# Generated by Django 4.2.27 on 2025-12-31 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_establishment_is_suspended_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishment',
            options={'verbose_name': 'منشأة', 'verbose_name_plural': 'المنشآت'},
        ),
    ]
