# Generated by Django 4.2.27 on 2026-01-01 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0012_alter_establishment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmark',
            options={'verbose_name': 'معلم سياحي', 'verbose_name_plural': 'المعالم السياحية'},
        ),
        migrations.AddField(
            model_name='landmark',
            name='conservation_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='حالة الحفاظ'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='estimated_age',
            field=models.CharField(blank=True, max_length=100, verbose_name='العمر التقريبي'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='historical_period',
            field=models.CharField(blank=True, max_length=100, verbose_name='الفترة التاريخية'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='موثق من مكتب السياحة'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='official_classification',
            field=models.CharField(blank=True, max_length=100, verbose_name='التصنيف الرسمي'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='unesco_listed',
            field=models.BooleanField(default=False, verbose_name='مدرج في يونسكو'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات التوثيق'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوثيق'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_landmarks', to=settings.AUTH_USER_MODEL, verbose_name='موثق بواسطة'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='best_visit_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='أفضل وقت للزيارة'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='climate_description',
            field=models.TextField(blank=True, verbose_name='وصف المناخ'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='landmark_type',
            field=models.CharField(blank=True, choices=[('historical', 'تاريخي'), ('natural', 'طبيعي'), ('religious', 'ديني'), ('archaeological', 'أثري'), ('cultural', 'ثقافي'), ('other', 'أخرى')], max_length=100),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='safety_instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات السلامة'),
        ),
    ]
