# Generated by Django 4.2.27 on 2026-01-01 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0013_alter_landmark_options_landmark_conservation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('stop_duration', models.PositiveIntegerField(default=30, help_text='بالدقائق', verbose_name='مدة التوقف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'verbose_name': 'نقطة مسار',
                'verbose_name_plural': 'نقاط المسار',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TouristRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='اسم المسار')),
                ('description', models.TextField(verbose_name='وصف المسار')),
                ('route_type', models.CharField(choices=[('historical', 'تاريخي'), ('natural', 'طبيعي'), ('religious', 'ديني'), ('cultural', 'ثقافي'), ('adventure', 'مغامرة'), ('family', 'عائلي')], default='historical', max_length=20, verbose_name='نوع المسار')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('moderate', 'متوسط'), ('difficult', 'صعب')], default='easy', max_length=20, verbose_name='مستوى الصعوبة')),
                ('estimated_duration', models.PositiveIntegerField(help_text='بالدقائق', verbose_name='المدة التقديرية')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='المسافة (كم)')),
                ('best_time', models.CharField(blank=True, max_length=100, verbose_name='أفضل وقت للزيارة')),
                ('tips', models.TextField(blank=True, verbose_name='نصائح للزوار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('waypoints', models.ManyToManyField(related_name='routes', through='places.RouteWaypoint', to='places.place', verbose_name='نقاط المسار')),
            ],
            options={
                'verbose_name': 'مسار سياحي',
                'verbose_name_plural': 'المسارات السياحية',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='routewaypoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.touristroute'),
        ),
        migrations.AlterUniqueTogether(
            name='routewaypoint',
            unique_together={('route', 'place')},
        ),
    ]
