# Generated by Django 4.2.27 on 2026-01-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_routewaypoint_touristroute_routewaypoint_route_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepoint',
            options={'verbose_name': 'نقطة خدمة', 'verbose_name_plural': 'نقاط الخدمات'},
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='has_disabled_access',
            field=models.BooleanField(default=False, verbose_name='مجهز لذوي الهمم'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='is_24_hours',
            field=models.BooleanField(default=False, verbose_name='يعمل 24 ساعة'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='service_type',
            field=models.CharField(choices=[('bank', 'بنك / صرافة'), ('atm', 'صراف آلي'), ('car_rental', 'تأجير سيارات'), ('restroom', 'دورة مياه'), ('mosque', 'مسجد'), ('parking', 'موقف سيارات'), ('hospital', 'مستشفى / مركز صحي'), ('pharmacy', 'صيدلية'), ('police', 'مركز شرطة'), ('gas_station', 'محطة وقود')], max_length=50, verbose_name='نوع الخدمة'),
        ),
    ]
