# Generated by Django 4.2.27 on 2026-01-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_servicepoint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='photography_rules',
            field=models.TextField(blank=True, help_text='مثال: مسموح بدون فلاش، ممنوع، مسموح برسوم', verbose_name='ضوابط التصوير'),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours_text',
            field=models.CharField(blank=True, help_text='مثال: يومياً من 8 صباحاً حتى 10 مساءً', max_length=200, verbose_name='ساعات العمل (نص)'),
        ),
        migrations.AddField(
            model_name='place',
            name='price_range',
            field=models.CharField(choices=[('low', '$ (اقتصادي)'), ('medium', '$$ (متوسط)'), ('high', '$$$ (فاخر)')], default='medium', max_length=20, verbose_name='مستوى الأسعار'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='is_open_status',
            field=models.BooleanField(default=True, verbose_name='مفتوح الآن (يدوي)'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
