# Generated by Django 4.2.27 on 2026-01-01 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0016_landmark_photography_rules_place_opening_hours_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.CreateModel(
            name='PlaceViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('referer', models.URLField(blank=True, max_length=500, verbose_name='الصفحة المرجعية')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='مفتاح الجلسة')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت المشاهدة')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='places.place', verbose_name='المعلم')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_views', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل مشاهدة',
                'verbose_name_plural': 'سجلات المشاهدات',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['-viewed_at'], name='places_plac_viewed__0f001c_idx'), models.Index(fields=['place'], name='places_plac_place_i_fca076_idx'), models.Index(fields=['ip_address'], name='places_plac_ip_addr_29a7c5_idx'), models.Index(fields=['user'], name='places_plac_user_id_36af7d_idx')],
            },
        ),
    ]
