# Generated by Django 4.2.27 on 2026-01-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_add_place_view_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='best_season',
            field=models.CharField(choices=[('all_year', 'طوال العام'), ('summer', 'الصيف'), ('winter', 'الشتاء'), ('spring', 'الربيع'), ('rainy', 'موسم الأمطار')], default='all_year', max_length=20, verbose_name='أفضل موسم للزيارة'),
        ),
        migrations.AddField(
            model_name='place',
            name='operational_status',
            field=models.CharField(choices=[('active', 'نشط ومفتوح'), ('closed', 'مغلق مؤقتاً'), ('maintenance', 'قيد الصيانة'), ('seasonal', 'موسمي'), ('dangerous', 'خطر - غير آمن للزيارة')], default='active', max_length=20, verbose_name='الحالة التشغيلية'),
        ),
        migrations.AddField(
            model_name='place',
            name='reopening_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إعادة الافتتاح المتوقع'),
        ),
        migrations.AddField(
            model_name='place',
            name='status_note',
            field=models.TextField(blank=True, help_text='سبب الإغلاق أو تحذير السلامة', verbose_name='ملاحظة الحالة'),
        ),
    ]
