# Generated by Django 4.2.27 on 2026-01-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_add_operational_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='update_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='photography_rules',
            field=models.TextField(blank=True, verbose_name='ضوابط التصوير'),
        ),
        migrations.AlterField(
            model_name='place',
            name='opening_hours_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='ساعات العمل (نص)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='status_note',
            field=models.TextField(blank=True, verbose_name='ملاحظة الحالة'),
        ),
    ]
