# Generated by Django Schema Hardening - 2026-01-13
# places/migrations/0020_schema_hardening.py

from django.db import migrations, models


def clean_place_data(apps, schema_editor):
    """Clean invalid data before adding constraints."""
    Place = apps.get_model('places', 'Place')
    
    # Fix out-of-range latitude
    Place.objects.filter(latitude__lt=-90).update(latitude=None)
    Place.objects.filter(latitude__gt=90).update(latitude=None)
    
    # Fix out-of-range longitude
    Place.objects.filter(longitude__lt=-180).update(longitude=None)
    Place.objects.filter(longitude__gt=180).update(longitude=None)
    
    # Fix out-of-range avg_rating
    Place.objects.filter(avg_rating__lt=0).update(avg_rating=0)
    Place.objects.filter(avg_rating__gt=5).update(avg_rating=5)


def clean_unit_data(apps, schema_editor):
    """Clean invalid unit prices."""
    EstablishmentUnit = apps.get_model('places', 'EstablishmentUnit')
    EstablishmentUnit.objects.filter(price__lt=0).update(price=0)


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_alter_establishment_update_note_and_more'),
    ]

    operations = [
        # 1. Clean data first
        migrations.RunPython(clean_place_data, migrations.RunPython.noop),
        migrations.RunPython(clean_unit_data, migrations.RunPython.noop),
        
        # 2. Add constraints to Place
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(
                check=models.Q(latitude__isnull=True) | models.Q(latitude__gte=-90, latitude__lte=90),
                name='place_latitude_range'
            ),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(
                check=models.Q(longitude__isnull=True) | models.Q(longitude__gte=-180, longitude__lte=180),
                name='place_longitude_range'
            ),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(
                check=models.Q(avg_rating__gte=0, avg_rating__lte=5),
                name='place_avg_rating_range'
            ),
        ),
        
        # 3. Add constraints to EstablishmentUnit
        migrations.AddConstraint(
            model_name='establishmentunit',
            constraint=models.CheckConstraint(
                check=models.Q(price__isnull=True) | models.Q(price__gte=0),
                name='unit_price_positive'
            ),
        ),
        
        # 4. Add indexes to Place for common queries
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_active', 'directorate'], name='place_active_dir_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category', 'is_active'], name='place_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['operational_status', 'is_active'], name='place_opstatus_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['-avg_rating', '-view_count'], name='place_rating_views_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='place_coords_idx'),
        ),
    ]
