# Generated by Django 4.2.27 on 2026-01-15 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0019_alter_establishment_update_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='حالة الاعتماد'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_establishments', to=settings.AUTH_USER_MODEL, verbose_name='معتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['approval_status'], name='places_esta_approva_00aa67_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['owner'], name='places_esta_owner_i_153a46_idx'),
        ),
    ]
