# Generated by Django 4.2.27 on 2026-01-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_schema_hardening'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='establishmentunit',
            name='unit_price_positive',
        ),
        migrations.RemoveConstraint(
            model_name='place',
            name='place_latitude_range',
        ),
        migrations.RemoveConstraint(
            model_name='place',
            name='place_longitude_range',
        ),
        migrations.RemoveConstraint(
            model_name='place',
            name='place_avg_rating_range',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_active_dir_idx',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_cat_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_opstatus_idx',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_rating_views_idx',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_coords_idx',
        ),
    ]
