# Generated by Django 4.2.27 on 2026-01-15 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0021_set_existing_establishments_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('phone', 'هاتف'), ('whatsapp', 'واتساب'), ('telegram', 'تيليجرام'), ('facebook', 'فيسبوك'), ('instagram', 'انستغرام'), ('tiktok', 'تيك توك'), ('snapchat', 'سناب شات'), ('youtube', 'يوتيوب'), ('website', 'موقع إلكتروني'), ('email', 'بريد إلكتروني'), ('google_maps', 'خرائط جوجل'), ('other', 'أخرى')], max_length=20, verbose_name='نوع جهة الاتصال')),
                ('carrier', models.CharField(blank=True, choices=[('sabafon', 'سبأفون'), ('yemen_mobile', 'يمن موبايل'), ('you', 'يو'), ('wai', 'واي'), ('landline', 'أرضي'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='الناقل/المشغل')),
                ('label', models.CharField(blank=True, help_text='مثال: الرقم الرئيسي، خدمة العملاء', max_length=60, verbose_name='التسمية')),
                ('value', models.CharField(help_text='رقم الهاتف أو الرابط أو البريد', max_length=255, verbose_name='القيمة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='جهة اتصال رئيسية')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_visible', models.BooleanField(default=True, verbose_name='مرئي للزوار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='places.establishment', verbose_name='المنشأة')),
            ],
            options={
                'verbose_name': 'جهة اتصال',
                'verbose_name_plural': 'جهات الاتصال',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['establishment', 'type', 'display_order'], name='places_esta_establi_88dd7d_idx'), models.Index(fields=['establishment', 'is_visible'], name='places_esta_establi_99af04_idx')],
            },
        ),
    ]
