# Generated by Django 4.2.27 on 2026-01-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_add_establishment_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات'),
        ),
        migrations.AddField(
            model_name='place',
            name='rating_distribution',
            field=models.JSONField(blank=True, default=dict, verbose_name='توزيع التقييمات'),
        ),
    ]
