# Generated by Django 4.2.27 on 2026-01-15 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0023_place_rating_count_place_rating_distribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establishment',
            old_name='is_open_status',
            new_name='is_open_now',
        ),
        migrations.AddField(
            model_name='establishment',
            name='open_status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='open_status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EstablishmentWorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='اليوم')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='وقت الفتح')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('is_closed_day', models.BooleanField(default=False, verbose_name='مغلق طوال اليوم')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='places.establishment')),
            ],
            options={
                'verbose_name': 'ساعات العمل',
                'verbose_name_plural': 'ساعات العمل',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.AddConstraint(
            model_name='establishmentworkinghour',
            constraint=models.UniqueConstraint(fields=('establishment', 'day_of_week'), name='unique_working_hour_per_day'),
        ),
    ]
