# Generated by Django 4.2.27 on 2026-01-15 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0024_rename_is_open_status_establishment_is_open_now_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='حالة الاعتماد'),
        ),
        migrations.CreateModel(
            name='EstablishmentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('current_step', models.IntegerField(default=1)),
                ('is_create_mode', models.BooleanField(default=True, help_text='True if creating new establishment, False if editing')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'تم الإرسال')], default='draft', max_length=20)),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='places.establishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مسودة منشأة',
                'verbose_name_plural': 'مسودات المنشآت',
                'ordering': ['-updated_at'],
            },
        ),
    ]
