# Generated by Django 4.2.27 on 2026-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0025_alter_establishment_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='cached_avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='متوسط التقييم'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='cached_rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='cached_review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المراجعات'),
        ),
    ]
