# Generated by Django 4.2.27 on 2026-01-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_remove_establishmentunit_unit_price_positive_and_more'),
        ('places', '0027_alter_amenity_name_alter_category_name_and_more'),
    ]

    operations = [
    ]
