# Generated by Django 4.2.27 on 2026-01-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0028_merge_20260119_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='commercial_registration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم السجل التجاري'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الترخيص'),
        ),
    ]
