# Generated by Django 4.2.27 on 2026-01-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0029_add_license_registration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='classification',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('family', 'Family Only')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='directorate',
            field=models.CharField(blank=True, choices=[('AL_DHIHAR', 'الظهار'), ('AL_MASHANNAH', 'المشنة'), ('JIBLA', 'جبلة'), ('AL_SADDAH', 'السدة'), ('BAADAN', 'بعدان'), ('AL_SABRA', 'السبرة'), ('AL_UDAYN', 'العدين'), ('HAZM_AL_UDAYN', 'حزم العدين'), ('FAR_AL_UDAYN', 'فرع العدين'), ('HUBISH', 'حبيش'), ('AL_MAKHADIR', 'المخادر'), ('AL_QAFR', 'القفر'), ('YARIM', 'يريم'), ('AL_RADMA', 'الرضمة'), ('AL_NANIYANI', 'السياني'), ('ZI_ALSUFAL', 'ذي السفال'), ('AL_MANDAR', 'المندر')], default='AL_DHIHAR', max_length=50, verbose_name='المديرية'),
        ),
        migrations.AlterField(
            model_name='place',
            name='road_condition',
            field=models.CharField(blank=True, choices=[('paved', 'Paved'), ('offroad', 'Off-road (4x4)')], default='paved', max_length=20),
        ),
    ]
