# Generated by Django 4.2.27 on 2026-01-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0030_alter_place_classification_alter_place_directorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
    ]
