# Generated by Django 4.2.27 on 2026-01-25 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0031_place_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDailyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='places.place')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['place', 'date'], name='places_plac_place_i_41f43f_idx')],
                'unique_together': {('place', 'date')},
            },
        ),
    ]
