# Generated by Django 4.2.27 on 2026-01-27 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0032_placedailyview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العرض')),
                ('description', models.TextField(blank=True, verbose_name='تفاصيل العرض')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر القديم')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر العرض')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='صورة العرض')),
                ('start_date', models.DateTimeField(verbose_name='بداية العرض')),
                ('end_date', models.DateTimeField(verbose_name='نهاية العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='places.establishment', verbose_name='المنشأة')),
            ],
            options={
                'verbose_name': 'عرض خاص',
                'verbose_name_plural': 'عروض خاصة',
                'ordering': ['-created_at'],
            },
        ),
    ]
