# Generated by Django 4.2.27 on 2026-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0033_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedailyview',
            name='contact_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
