# Generated by Django 4.2.27 on 2026-02-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0034_placedailyview_contact_clicks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'مكان', 'verbose_name_plural': 'الأماكن'},
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_active'], name='places_plac_is_acti_7fcf18_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_featured'], name='places_plac_is_feat_c17c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['avg_rating'], name='places_plac_avg_rat_3ca014_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['directorate'], name='places_plac_directo_21adc0_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['created_at'], name='places_plac_created_6fc9cf_idx'),
        ),
    ]
