# Generated by Django 4.2.27 on 2025-12-29 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_partnerprofile_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='info_request_message',
            field=models.TextField(blank=True, verbose_name='رسالة طلب المعلومات'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partners', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('needs_info', 'بحاجة إلى معلومات إضافية')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
