# Generated by Django 4.2.27 on 2025-12-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_partner_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='نبذة تعريفية'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers/', verbose_name='صورة غلاف'),
        ),
    ]
