# Generated by Django 4.2.27 on 2026-01-01 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_email_verification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('username', models.CharField(max_length=150, verbose_name='اسم المستخدم')),
                ('registration_type', models.CharField(choices=[('tourist', 'سائح'), ('partner', 'شريك')], default='tourist', max_length=20, verbose_name='نوع التسجيل')),
                ('status', models.CharField(choices=[('success', 'ناجح'), ('failed', 'فاشل'), ('pending', 'معلق')], default='pending', max_length=20, verbose_name='الحالة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('referer', models.URLField(blank=True, max_length=500, verbose_name='الصفحة المرجعية')),
                ('failure_reason', models.TextField(blank=True, verbose_name='سبب الفشل')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تسجيل',
                'verbose_name_plural': 'سجلات التسجيل',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_userr_created_8f2c99_idx'), models.Index(fields=['ip_address'], name='users_userr_ip_addr_611cb6_idx'), models.Index(fields=['email'], name='users_userr_email_204e65_idx'), models.Index(fields=['status'], name='users_userr_status_108414_idx')],
            },
        ),
    ]
