# Generated by Django 4.2.27 on 2026-01-01 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_registration_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_or_email', models.CharField(max_length=255, verbose_name='اسم المستخدم أو البريد')),
                ('status', models.CharField(choices=[('success', 'ناجح'), ('failed', 'فاشل'), ('blocked', 'محظور')], max_length=20, verbose_name='الحالة')),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_credentials', 'بيانات اعتماد غير صحيحة'), ('account_suspended', 'حساب موقوف'), ('account_rejected', 'حساب مرفوض'), ('email_not_verified', 'بريد غير مؤكد'), ('account_locked', 'حساب مقفل مؤقتاً'), ('rate_limited', 'تجاوز الحد المسموح'), ('other', 'سبب آخر')], max_length=50, verbose_name='سبب الفشل')),
                ('failure_details', models.TextField(blank=True, verbose_name='تفاصيل الفشل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت المحاولة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل دخول',
                'verbose_name_plural': 'سجلات الدخول',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_userl_created_4a7592_idx'), models.Index(fields=['ip_address'], name='users_userl_ip_addr_5ba078_idx'), models.Index(fields=['username_or_email'], name='users_userl_usernam_63f9ef_idx'), models.Index(fields=['status'], name='users_userl_status_461cfd_idx'), models.Index(fields=['user'], name='users_userl_user_id_1db150_idx')],
            },
        ),
    ]
