# Generated by Django 4.2.27 on 2026-01-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='commercial_registry_file',
            field=models.FileField(blank=True, null=True, upload_to='partners/registries/', verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المنظمة/النشاط'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تقديم الطلب'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='partners/id_cards/', verbose_name='صورة البطاقة الشخصية'),
        ),
    ]
