# Generated by Django Schema Hardening - 2026-01-13
# users/migrations/0009_schema_hardening.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_role_permissions'),
    ]

    operations = [
        # 1. Add indexes for User queries
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_staff'], name='user_active_staff_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='user_joined_idx'),
        ),
        
        # 2. Add indexes for PartnerProfile queries
        migrations.AddIndex(
            model_name='partnerprofile',
            index=models.Index(fields=['status', 'is_approved'], name='partner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerprofile',
            index=models.Index(fields=['-created_at'], name='partner_created_idx'),
        ),
    ]
