# Generated by Django 4.2.27 on 2026-01-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_schema_hardening'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='partnerprofile',
            name='partner_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnerprofile',
            name='partner_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_active_staff_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_joined_idx',
        ),
    ]
