# Generated by Django 4.2.27 on 2026-01-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_partner_upgrade_fields'),
        ('users', '0010_remove_partnerprofile_partner_status_idx_and_more'),
    ]

    operations = [
    ]
