# Generated by Django 4.2.27 on 2026-01-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20260119_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الاهتمام')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome class (e.g., fa-tree)', max_length=50, verbose_name='الأيقونة')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, to='users.interest', verbose_name='الاهتمامات'),
        ),
    ]
