# Generated by Django 4.2.27 on 2026-01-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_interest_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationlog',
            name='registration_type',
            field=models.CharField(choices=[('tourist', 'سائح'), ('partner', 'شريك'), ('api', 'تسجيل API')], default='tourist', max_length=20, verbose_name='نوع التسجيل'),
        ),
    ]
