# Generated by Django 4.2.27 on 2026-01-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userregistrationlog_registration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='last_upgrade_request',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر طلب ترقية'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='subscription_end',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='upgrade_request_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد محاولات طلب الترقية'),
        ),
    ]
