# Generated by Django 4.2.27 on 2026-01-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='seasons/covers/', verbose_name='صورة الغلاف')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفعالية')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('start_datetime', models.DateTimeField(verbose_name='تاريخ ووقت البداية')),
                ('end_datetime', models.DateTimeField(verbose_name='تاريخ ووقت النهاية')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='صورة الغلاف')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر التذكرة')),
                ('event_type', models.CharField(choices=[('festival', 'مهرجان'), ('concert', 'حفلة'), ('exhibition', 'معرض'), ('workshop', 'ورشة عمل'), ('sports', 'رياضة'), ('other', 'آخر')], default='other', max_length=20, verbose_name='نوع الفعالية')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.season', verbose_name='الموسم')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
