# Generated by Django 4.2.27 on 2026-01-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('festival', 'مهرجان'), ('concert', 'حفلة'), ('exhibition', 'معرض'), ('workshop', 'ورشة عمل'), ('sports', 'رياضة'), ('tour', 'جولة'), ('cultural', 'ثقافي'), ('market', 'سوق'), ('adventure', 'مغامرة'), ('other', 'آخر')], default='other', max_length=20, verbose_name='نوع الفعالية'),
        ),
    ]
