# Generated by Django 4.2.27 on 2025-12-30 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم المجتمع')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(verbose_name='وصف المجتمع')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='communities/covers/', verbose_name='صورة الغلاف')),
                ('is_official', models.BooleanField(default=False, verbose_name='مجموعة رسمية')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL, verbose_name='مؤسس المجتمع')),
            ],
            options={
                'verbose_name': 'مجتمع سياحي',
                'verbose_name_plural': 'المجتمعات السياحية',
                'ordering': ['-is_official', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='محتوى المنشور')),
                ('image', models.ImageField(blank=True, null=True, upload_to='communities/posts/', verbose_name='صورة مرفقة')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL, verbose_name='الناشر')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communities.community', verbose_name='المجتمع')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='الإعجابات')),
            ],
            options={
                'verbose_name': 'منشور مجتمعي',
                'verbose_name_plural': 'منشورات المجتمع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MEMBER', 'عضو'), ('MODERATOR', 'مشرف'), ('ADMIN', 'مدير')], default='MEMBER', max_length=20, verbose_name='الدور')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضوية المجتمع',
                'verbose_name_plural': 'عضويات المجتمعات',
                'unique_together': {('user', 'community')},
            },
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='joined_communities', through='communities.CommunityMembership', to=settings.AUTH_USER_MODEL, verbose_name='الأعضاء'),
        ),
    ]
