# Generated by Django 4.2.27 on 2025-12-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_establishment_update_note_and_more'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='linked_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_mentions', to='places.place', verbose_name='المعلم السياحي المرتبط'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(choices=[('EXPERIENCE', 'تجربة زيارة'), ('ADVICE', 'نصيحة'), ('WARNING', 'تحذير/تنبيه'), ('GENERAL', 'عام')], default='GENERAL', max_length=20, verbose_name='نوع المنشور'),
        ),
    ]
