# Generated by Django 4.2.27 on 2025-12-21 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='clicks_count',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='target_link',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='title',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='duration_days',
            field=models.PositiveIntegerField(default=7, help_text='Duration in days'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='places.place'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(),
        ),
    ]
