# Generated by Django 4.2.27 on 2025-12-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_advertisement_clicks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/receipts/'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
