# Generated by Django 4.2.27 on 2025-12-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_advertisement_receipt_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(default='New Ad', max_length=200),
        ),
    ]
