# Generated by Django 4.2.27 on 2025-12-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_advertisement_description_advertisement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Reason for rejection or reupload request'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('payment_issue', 'Payment Reupload Required')], default='pending', max_length=20),
        ),
    ]
