# Generated by Django 4.2.27 on 2025-12-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_advertisement_admin_notes_advertisement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
