# Generated by Django 4.2.27 on 2025-12-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_advertisement_clicks_advertisement_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price', max_digits=10, null=True),
        ),
    ]
