# Generated by Django 4.2.27 on 2025-12-31 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0010_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Private notes for admins'),
        ),
        migrations.AddField(
            model_name='request',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of field changes {field: new_value}'),
        ),
        migrations.AddField(
            model_name='request',
            name='original_data',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of original data for comparison'),
        ),
        migrations.AddField(
            model_name='request',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='request',
            name='target_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='admin_response',
            field=models.TextField(blank=True, help_text="Admin's response or feedback"),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, help_text="User's description of the request"),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('UPGRADE_PARTNER', 'Upgrade To Partner'), ('ADD_PLACE', 'Add Place'), ('UPDATE_INFO', 'Update Information'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_INFO', 'Needs Info'), ('CONDITIONAL_APPROVAL', 'Conditional Approval')], default='PENDING', max_length=30),
        ),
    ]
