# Generated by Django 4.2.27 on 2025-12-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_request_admin_notes_request_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='conditions',
            field=models.TextField(blank=True, verbose_name='شروط الموافقة'),
        ),
        migrations.AddField(
            model_name='request',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلة التعديل'),
        ),
    ]
