# Generated by Django 4.2.27 on 2025-12-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_request_conditions_request_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='audit_logs/', verbose_name='مستند مرفق'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, verbose_name='سبب القرار'),
        ),
        migrations.AddField(
            model_name='request',
            name='decision_doc',
            field=models.FileField(blank=True, null=True, upload_to='requests/decisions/', verbose_name='مستند القرار'),
        ),
    ]
