# Generated by Django 4.2.27 on 2025-12-31 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0014_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(help_text='Complete JSON snapshot of the entity at this version')),
                ('reason', models.CharField(blank=True, help_text="Reason for this version (e.g., 'Before update', 'Before approval')", max_length=200)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='management.request')),
            ],
            options={
                'verbose_name': 'إصدار الكيان',
                'verbose_name_plural': 'إصدارات الكيانات',
                'ordering': ['-created_at', '-version_number'],
                'unique_together': {('content_type', 'object_id', 'version_number')},
            },
        ),
    ]
