# Generated by Django 4.2.27 on 2025-12-31 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_entity_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'إعلان', 'verbose_name_plural': 'الإعلانات'},
        ),
    ]
