# Generated by Django 4.2.27 on 2025-12-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_advertisement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة'), ('active', 'نشط'), ('paused', 'متوقف مؤقتاً'), ('expired', 'منتهي'), ('rejected', 'مرفوض'), ('payment_issue', 'مشكلة في الدفع')], default='pending', max_length=20),
        ),
    ]
