# Generated by Django 4.2.27 on 2026-01-01 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0018_requeststatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('UPGRADE_PARTNER', 'ترقية للشريك'), ('ADD_PLACE', 'إضافة مكان جديد'), ('UPDATE_INFO', 'تحديث معلومات'), ('EDIT_NAME', 'تعديل الاسم'), ('EDIT_DESC', 'تعديل الوصف'), ('EDIT_LOCATION', 'تعديل الموقع'), ('EDIT_CATEGORY', 'تعديل التصنيف'), ('EDIT_MEDIA', 'تعديل الصور/الفيديو'), ('VERIFY_ESTABLISHMENT', 'طلب توثيق'), ('CREATE_AD', 'إنشاء إعلان'), ('OTHER', 'أخرى')], max_length=50),
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('APPROVE', 'موافقة'), ('REJECT', 'رفض'), ('REQUEST_INFO', 'طلب معلومات'), ('CONDITIONAL', 'موافقة مشروطة'), ('REVOKE', 'إلغاء')], max_length=20)),
                ('reason', models.TextField(help_text='سبب القرار')),
                ('conditions', models.TextField(blank=True, help_text='الشروط (للموافقة المشروطة)')),
                ('deadline', models.DateTimeField(blank=True, help_text='مهلة التنفيذ', null=True)),
                ('decision_document', models.FileField(blank=True, help_text='مستند القرار الرسمي', null=True, upload_to='decisions/documents/')),
                ('is_final', models.BooleanField(default=True, help_text='قرار نهائي')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='management.request')),
            ],
            options={
                'verbose_name': 'قرار الموافقة',
                'verbose_name_plural': 'قرارات الموافقات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'decision'], name='management__request_1a2c52_idx'), models.Index(fields=['decided_by', 'created_at'], name='management__decided_70f0c0_idx')],
            },
        ),
    ]
