# Generated by Django 4.2.27 on 2026-01-02 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0018_add_operational_status'),
        ('management', '0019_alter_request_request_type_approvaldecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('MEDICAL', 'طوارئ طبية'), ('SECURITY', 'خطر أمني'), ('LOST', 'ضياع'), ('WEATHER', 'سيول/طقس'), ('ACCIDENT', 'حادث مروري')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط - جاري التعامل'), ('RESPONDING', 'تم الاستجابة'), ('RESOLVED', 'تم الحل'), ('FALSE_ALARM', 'بلاغ خاطئ')], default='ACTIVE', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Battery level, signal strength, etc.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('relation', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('zone_type', models.CharField(choices=[('FLOOD', 'مجاري سيول'), ('SECURITY', 'منطقة أمنية'), ('RESTRICTED', 'منطقة محظورة'), ('DANGEROUS_ROAD', 'طريق خطر')], max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالي'), ('CRITICAL', 'خطر جداً')], max_length=20)),
                ('polygon', models.JSONField(help_text='List of [lat, lon] points defining the zone')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('safety_status', models.CharField(max_length=20)),
                ('warnings', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'سيارة صغيرة (Sedan)'), ('SUV', 'سيارة عائلية (SUV)'), ('4X4', 'دفع رباعي (4x4)'), ('MOTORCYCLE', 'دراجة نارية')], default='SEDAN', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='attachment',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='diff',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='الفروقات'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى'),
        ),
        migrations.AddField(
            model_name='request',
            name='expected_completion_at',
            field=models.DateTimeField(blank=True, help_text='SLA Deadline', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالي')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name', 'record_id'], name='management__table_n_e4777b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='management__user_id_1049bd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='management__action_3058f1_idx'),
        ),
        migrations.AddField(
            model_name='vehicleprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routelog',
            name='destination_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
        migrations.AddField(
            model_name='routelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalassignment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='management.request'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='management__latitud_4a763b_idx'),
        ),
    ]
