# Generated by Django 4.2.27 on 2026-01-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_approvalassignment_emergencyalert_emergencycontact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['user', '-created_at'], name='management__user_id_8d3a29_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status', '-created_at'], name='management__status_5f9002_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['request_type'], name='management__request_ccc24e_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['assigned_to'], name='management__assigne_003871_idx'),
        ),
    ]
