# Generated by Django 4.2.27 on 2026-01-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityversion',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for this version', max_length=200),
        ),
    ]
