# Generated by Django 4.2.27 on 2026-01-15 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_alter_establishment_update_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0022_alter_entityversion_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة'), ('active', 'نشط'), ('paused', 'متوقف مؤقتاً'), ('expired', 'منتهي'), ('rejected', 'مرفوض'), ('payment_issue', 'مشكلة في الدفع')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='PendingChange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف')),
                ('entity_type', models.CharField(choices=[('establishment', 'منشأة')], default='establishment', max_length=50, verbose_name='نوع الكيان')),
                ('field_name', models.CharField(choices=[('name', 'الاسم'), ('description', 'الوصف')], max_length=50, verbose_name='اسم الحقل')),
                ('old_value', models.TextField(verbose_name='القيمة القديمة')),
                ('new_value', models.TextField(verbose_name='القيمة الجديدة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_note', models.TextField(blank=True, verbose_name='ملاحظة المراجعة')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='places.establishment', verbose_name='المنشأة')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_changes', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_changes', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة')),
            ],
            options={
                'verbose_name': 'تغيير معلق',
                'verbose_name_plural': 'تغييرات معلقة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='management__status_0c106d_idx'), models.Index(fields=['establishment', 'status'], name='management__establi_8e14b6_idx'), models.Index(fields=['requested_by'], name='management__request_22b625_idx')],
            },
        ),
    ]
