# Generated by Django Schema Hardening - 2026-01-13
# management/migrations/0023_schema_hardening.py

from django.db import migrations, models


def clean_advertisement_data(apps, schema_editor):
    """Clean invalid advertisement data."""
    Advertisement = apps.get_model('management', 'Advertisement')
    
    # Fix negative duration
    Advertisement.objects.filter(duration_days__lt=1).update(duration_days=7)
    
    # Fix discount_price > price
    for ad in Advertisement.objects.filter(
        discount_price__isnull=False, 
        price__isnull=False
    ):
        if ad.discount_price > ad.price:
            ad.discount_price = ad.price
            ad.save(update_fields=['discount_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_entityversion_reason'),
    ]

    operations = [
        # 1. Clean data first
        migrations.RunPython(clean_advertisement_data, migrations.RunPython.noop),
        
        # 2. Add constraints to Advertisement
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.CheckConstraint(
                check=models.Q(duration_days__gte=1),
                name='ad_duration_positive'
            ),
        ),
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.CheckConstraint(
                check=models.Q(end_date__isnull=True) | models.Q(start_date__lte=models.F('end_date')),
                name='ad_date_order'
            ),
        ),
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(discount_price__isnull=True) |
                    models.Q(price__isnull=True) |
                    models.Q(discount_price__lte=models.F('price'))
                ),
                name='ad_discount_lte_price'
            ),
        ),
        
        # 3. Partial unique constraint: only one pending/active ad per place
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.UniqueConstraint(
                fields=['place'],
                condition=models.Q(status__in=['pending', 'active']),
                name='ad_unique_active_per_place'
            ),
        ),
        
        # 4. Add indexes for Advertisement queries
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='ad_status_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['owner', 'status'], name='ad_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['place', 'status'], name='ad_place_status_idx'),
        ),
        
        # 5. Add indexes for Request (GenericFK)
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='request_gfk_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status', '-created_at'], name='request_status_date_idx'),
        ),
        
        # 6. Add indexes for EntityVersion
        migrations.AddIndex(
            model_name='entityversion',
            index=models.Index(fields=['content_type', 'object_id'], name='version_gfk_idx'),
        ),
        
        # 7. Add indexes for AuditLog
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='audit_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'table_name'], name='audit_action_table_idx'),
        ),
    ]
