# Generated by Django Schema Hardening - 2026-01-13
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_schema_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click')], max_length=10)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='management.advertisement')),
            ],
            options={
                'verbose_name': 'تفاعل إعلان',
                'verbose_name_plural': 'تفاعلات الإعلانات',
            },
        ),
        migrations.AddIndex(
            model_name='adinteraction',
            index=models.Index(fields=['ad', 'interaction_type', 'session_key'], name='ad_interact_session_idx'),
        ),
        migrations.AddIndex(
            model_name='adinteraction',
            index=models.Index(fields=['created_at'], name='ad_interact_date_idx'),
        ),
    ]
