# Generated by Django 4.2.27 on 2026-01-16 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0023_add_pending_change_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('delete', 'Delete'), ('access_denied', 'Access Denied')], db_index=True, max_length=20, verbose_name='Action')),
                ('file_path', models.CharField(max_length=500, verbose_name='File Path')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='File Type')),
                ('file_size', models.PositiveIntegerField(null=True, verbose_name='File Size (bytes)')),
                ('entity_type', models.CharField(blank=True, max_length=100, verbose_name='Entity Type')),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name='Entity ID')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'File Audit Log',
                'verbose_name_plural': 'File Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='management__action_1a16ab_idx'), models.Index(fields=['user', 'created_at'], name='management__user_id_bf5454_idx'), models.Index(fields=['entity_type', 'entity_id'], name='management__entity__2a07df_idx')],
            },
        ),
    ]
