# Generated by Django 4.2.27 on 2026-01-16 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('management', '0024_fileauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Rule Name')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated list of keywords. If any match, the action is triggered.')),
                ('is_regex', models.BooleanField(default=False, verbose_name='Is Regex Pattern?')),
                ('action', models.CharField(choices=[('block', 'Block/Auto-Reject'), ('flag', 'Flag for Review'), ('allow', 'Allow/Auto-Approve')], default='flag', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_moderation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low (Warning)'), ('medium', 'Medium (Review/Flag)'), ('high', 'High (Block)')], default='medium', max_length=10)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('any', 'Any')], default='any', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banned Word',
                'verbose_name_plural': 'Banned Words',
                'ordering': ['term'],
                'indexes': [models.Index(fields=['is_active', 'severity'], name='management__is_acti_d011b3_idx'), models.Index(fields=['language', 'is_active'], name='management__languag_12ed67_idx')],
                'unique_together': {('term', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ModerationQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_snippet', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('flagged_reason', models.CharField(blank=True, max_length=255)),
                ('moderation_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='management__status_813a1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_snapshot', models.TextField(verbose_name='Flagged Content')),
                ('matched_terms', models.JSONField(default=list)),
                ('severity', models.CharField(max_length=20)),
                ('action_taken', models.CharField(choices=[('warned', 'Warned'), ('blocked', 'Blocked'), ('flagged', 'Flagged for Review'), ('allowed', 'Allowed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Event',
                'verbose_name_plural': 'Moderation Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='management__severit_5d7e8e_idx'), models.Index(fields=['action_taken'], name='management__action__0b18cc_idx')],
            },
        ),
    ]
