# Generated by Django 4.2.27 on 2026-01-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_ad_interaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEmergencyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الجهة')),
                ('number', models.CharField(max_length=20, verbose_name='رقم الطوارئ')),
                ('icon', models.CharField(choices=[('fas fa-ambulance', 'Ambulance (Red)'), ('fas fa-user-shield', 'Police (Blue)'), ('fas fa-fire-extinguisher', 'Fire (Orange)'), ('fas fa-hospital', 'Hospital (Green)'), ('fas fa-phone', 'General Phone')], default='fas fa-phone', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='وصف مختصر')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'رقم طوارئ عام',
                'verbose_name_plural': 'أرقام الطوارئ العامة',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ibb Guide', max_length=100)),
                ('email', models.EmailField(default='info@ibbguide.com', max_length=254)),
                ('phone_number', models.CharField(default='+967-12345678', max_length=20)),
                ('address', models.TextField(blank=True, default='Ibb, Yemen')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Format: 9677xxxxxxx', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.RemoveConstraint(
            model_name='advertisement',
            name='ad_duration_positive',
        ),
        migrations.RemoveConstraint(
            model_name='advertisement',
            name='ad_date_order',
        ),
        migrations.RemoveConstraint(
            model_name='advertisement',
            name='ad_discount_lte_price',
        ),
        migrations.RemoveConstraint(
            model_name='advertisement',
            name='ad_unique_active_per_place',
        ),
        migrations.RemoveIndex(
            model_name='advertisement',
            name='ad_status_dates_idx',
        ),
        migrations.RemoveIndex(
            model_name='advertisement',
            name='ad_owner_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='advertisement',
            name='ad_place_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_action_table_idx',
        ),
        migrations.RemoveIndex(
            model_name='entityversion',
            name='version_gfk_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_gfk_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_status_date_idx',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة'), ('active', 'نشط'), ('paused', 'متوقف مؤقتاً'), ('expired', 'منتهي'), ('rejected', 'مرفوض'), ('payment_issue', 'مشكلة في الدفع')], default='draft', max_length=20),
        ),
    ]
