# Generated by Django 4.2.27 on 2026-01-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_moderationrule_bannedword_moderationqueueitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-mosque', help_text='مثال: fas fa-mosque', max_length=50, verbose_name='أيقونة FontAwesome')),
                ('color', models.CharField(choices=[('primary', 'Primary (Blue)'), ('secondary', 'Secondary (Grey)'), ('success', 'Success (Green)'), ('danger', 'Danger (Red)'), ('warning', 'Warning (Yellow)'), ('info', 'Info (Cyan)')], default='primary', max_length=50, verbose_name='لون الأيقونة')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='culture/', verbose_name='صورة 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='culture/', verbose_name='صورة 2')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مَعلم ثقافي',
                'verbose_name_plural': 'المعالم الثقافية',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='الجهة')),
                ('number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف المختصر')),
                ('icon', models.CharField(help_text='مثال: fas fa-ambulance', max_length=50, verbose_name='أيقونة FontAwesome')),
                ('color', models.CharField(choices=[('danger', 'أحمر (خطر)'), ('warning', 'أصفر (تحذير)'), ('success', 'أخضر (نجاح)'), ('primary', 'أزرق (أساسي)'), ('info', 'سماوي (معلومات)'), ('dark', 'داكن')], default='danger', max_length=20, verbose_name='اللون')),
                ('is_primary_card', models.BooleanField(default=False, help_text='تظهر في أعلى الصفحة كبطاقة كبيرة (مثل: الشرطة، الإسعاف)', verbose_name='عرض كبطاقة كبيرة')),
                ('is_hospital', models.BooleanField(default=False, help_text='تظهر في قائمة المستشفيات', verbose_name='مستشفى؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'رقم طوارئ عام',
                'verbose_name_plural': 'أرقام الطوارئ العامة',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SafetyGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='التفاصيل')),
                ('icon', models.CharField(max_length=50, verbose_name='أيقونة FontAwesome')),
                ('color', models.CharField(choices=[('danger', 'أحمر (خطر)'), ('warning', 'أصفر (تحذير)'), ('success', 'أخضر (نجاح)'), ('primary', 'أزرق (أساسي)')], default='primary', max_length=20, verbose_name='اللون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'إرشادات السلامة',
                'verbose_name_plural': 'إرشادات السلامة',
                'ordering': ['order'],
            },
        ),
    ]
