# Generated by Django 4.2.27 on 2026-01-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_publicemergencynumber_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL identifier (e.g., 'about', 'terms')", unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='HTML content allowed')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
