# Generated by Django 4.2.27 on 2026-01-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_culturallandmark_publicemergencycontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان الرئيسي')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='العنوان الفرعي')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='صورة الخلفية')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='نص الزر')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='رابط الزر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'شريحة العرض (Hero Slide)',
                'verbose_name_plural': 'شرائح العرض الرئيسية',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SidebarWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(help_text='يمكنك استخدام HTML هنا', verbose_name='المحتوى HTML')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_visible', models.BooleanField(default=True, verbose_name='ظاهر')),
            ],
            options={
                'verbose_name': 'وجت جانبي',
                'verbose_name_plural': 'وجتات الشريط الجانبي',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='دليل إب السياحي', max_length=200, verbose_name='اسم الموقع')),
                ('logo', models.ImageField(default='site/default_logo.png', upload_to='site/', verbose_name='الشعار')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=20, verbose_name='اللون الأساسي')),
                ('footer_text', models.TextField(blank=True, verbose_name='نص الفوتر')),
                ('meta_description', models.TextField(blank=True, verbose_name='وصف الموقع (SEO)')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='الكلمات المفتاحية')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('role', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة مختصرة')),
                ('image', models.ImageField(upload_to='team/', verbose_name='الصورة الشخصية')),
                ('twitter', models.URLField(blank=True, verbose_name='تويتر')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكد إن')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'عضو فريق',
                'verbose_name_plural': 'فريق العمل',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='transport/', verbose_name='الشعار')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الحجز')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب')),
                ('description', models.TextField(blank=True, verbose_name='نبذة عن الشركة')),
                ('destinations', models.CharField(help_text='مثال: صنعاء، عدن، الحديدة', max_length=200, verbose_name='الوجهات الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'شركة نقل',
                'verbose_name_plural': 'شركات النقل',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('url', models.CharField(max_length=200, verbose_name='الرابط')),
                ('location', models.CharField(choices=[('header', 'القائمة العلوية (Header)'), ('footer', 'القائمة السفلية (Footer)'), ('sidebar', 'القائمة الجانبية (Sidebar)')], max_length=20, verbose_name='المكان')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='management.menu', verbose_name='العنصر الأب')),
            ],
            options={
                'verbose_name': 'قائمة',
                'verbose_name_plural': 'القوائم',
                'ordering': ['location', 'order'],
            },
        ),
    ]
