# Generated by Django 4.2.27 on 2026-01-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_staticpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(help_text='Card background image', upload_to='bento/')),
                ('link', models.CharField(help_text="URL name (e.g., 'majesty_stays') or absolute path", max_length=200)),
                ('css_class', models.CharField(choices=[('normal', 'Normal (1x1)'), ('bento-large', 'Large (2x1)'), ('bento-tall', 'Tall (1x2)')], default='normal', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GuideCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='guides/')),
                ('link', models.CharField(help_text='URL name or path', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
