# Generated by Django 4.2.27 on 2026-01-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_heroslide_sidebarwidget_sitesetting_teammember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='visible_for_admins',
            field=models.BooleanField(default=True, verbose_name='ظاهر للمسؤولين'),
        ),
        migrations.AddField(
            model_name='menu',
            name='visible_for_guests',
            field=models.BooleanField(default=True, verbose_name='ظاهر للزوار'),
        ),
        migrations.AddField(
            model_name='menu',
            name='visible_for_users',
            field=models.BooleanField(default=True, verbose_name='ظاهر للمستخدمين المسجلين'),
        ),
    ]
