# Generated by Django 4.2.27 on 2026-01-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_bentoitem_guidecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('url', models.CharField(max_length=200)),
                ('column', models.CharField(choices=[('tourism', 'السياحة'), ('company', 'الشركة'), ('explore', 'استكشف'), ('social', 'التواصل الاجتماعي')], default='company', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'رابط Footer',
                'verbose_name_plural': 'روابط Footer',
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuickAccessItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('icon', models.CharField(help_text='FontAwesome class', max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'عنصر وصول سريع',
                'verbose_name_plural': 'الوصول السريع',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SidebarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('url', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('section', models.CharField(choices=[('main', 'القسم الرئيسي'), ('features', 'مميزات'), ('services', 'خدمات')], default='main', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'عنصر قائمة جانبية',
                'verbose_name_plural': 'القائمة الجانبية',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('url', models.CharField(help_text="URL name (e.g., 'home') or absolute path (/about/)", max_length=200)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome class (e.g., fas fa-home)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='management.menuitem', verbose_name='القائمة الأب')),
            ],
            options={
                'verbose_name': 'عنصر قائمة رئيسية',
                'verbose_name_plural': 'القائمة الرئيسية',
                'ordering': ['order'],
            },
        ),
    ]
