# Generated by Django 4.2.27 on 2026-01-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_menu_visible_for_admins_menu_visible_for_guests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='مثال: Facebook, Twitter', max_length=50, verbose_name='الاسم')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('icon', models.CharField(blank=True, help_text='مثال: fab fa-facebook', max_length=50, verbose_name='أيقونة FontAwesome')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'رابط تواصل اجتماعي',
                'verbose_name_plural': 'روابط التواصل الاجتماعي',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني للتواصل'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف للتواصل'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='copyright_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='نص الحقوق'),
        ),
    ]
