# Generated by Django 4.2.27 on 2026-01-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_footerlink_quickaccessitem_sidebaritem_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Leave empty to use default image', null=True, upload_to='hero/', verbose_name='صورة الخلفية'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_subtitle',
            field=models.CharField(default='اكتشف سحر الطبيعة، وتاريخ الحضارة في اللواء الأخضر', max_length=300, verbose_name='وصف الهيرو'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(default='إب.. جنة الله في أرضه', max_length=200, verbose_name='عنوان الهيرو'),
        ),
    ]
