# Generated by Django 4.2.27 on 2026-01-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_sociallink_sitesetting_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarwidget',
            name='pages',
            field=models.JSONField(blank=True, default=list, help_text='["home", "places"] list of url names', verbose_name='الصفحات'),
        ),
        migrations.AddField(
            model_name='sidebarwidget',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='["guest", "user", "admin"]', verbose_name='الأدوار'),
        ),
        migrations.AddField(
            model_name='sidebarwidget',
            name='widget_type',
            field=models.CharField(choices=[('text', 'نص (Text)'), ('links', 'روابط (Links)'), ('stats', 'إحصائيات (Statistics)'), ('cta', 'دعوة لاتخاذ إجراء (CTA)'), ('custom_html', 'HTML مخصص')], default='text', max_length=20, verbose_name='نوع الوجت'),
        ),
        migrations.AlterField(
            model_name='sidebarwidget',
            name='content',
            field=models.TextField(blank=True, help_text='للنص، HTML، أو رابط زر CTA', verbose_name='المحتوى'),
        ),
        migrations.CreateModel(
            name='SidebarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='العنوان')),
                ('url', models.CharField(max_length=300, verbose_name='الرابط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='management.sidebarwidget', verbose_name='الويدجت')),
            ],
            options={
                'verbose_name': 'رابط جانبي',
                'verbose_name_plural': 'روابط جانبية',
                'ordering': ['order'],
            },
        ),
    ]
