# Generated by Django 4.2.27 on 2026-01-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_sidebarwidget_pages_sidebarwidget_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='للعرض في لوحة التحكم', max_length=200, verbose_name='عنوان القسم')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section - العرض الرئيسي'), ('featured_grid', 'Featured Grid - شبكة المميزات'), ('quick_access', 'Quick Access - الوصول السريع'), ('partners', 'Partners Slider - شريط الشركاء'), ('custom_html', 'Custom HTML - محتوى مخصص')], default='custom_html', max_length=50, verbose_name='نوع القسم')),
                ('content', models.TextField(blank=True, help_text='يستخدم فقط مع نوع Custom HTML', verbose_name='المحتوى (HTML)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='ظاهر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'قسم الصفحة الرئيسية',
                'verbose_name_plural': 'أقسام الصفحة الرئيسية',
                'ordering': ['order'],
            },
        ),
    ]
