# Generated by Django 4.2.27 on 2026-01-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_homepagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('place_list', 'دليل الأماكن (Place List)'), ('nature_list', 'الطبيعة (Nature)'), ('investment_list', 'الاستثمار (Investment)'), ('events_list', 'المناسبات (Events)')], max_length=50, unique=True, verbose_name='الصفحة')),
                ('hero_title', models.CharField(default='استكشف الأماكن', max_length=200, verbose_name='عنوان البانر')),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, verbose_name='وصف البانر')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/hero/', verbose_name='صورة البانر')),
                ('show_search', models.BooleanField(default=True, verbose_name='إظهار البحث')),
                ('show_category_filter', models.BooleanField(default=True, verbose_name='إظهار فلتر التصنيف')),
                ('show_rating_filter', models.BooleanField(default=True, verbose_name='إظهار فلتر التقييم')),
                ('show_price_filter', models.BooleanField(default=False, verbose_name='إظهار فلتر الأسعار')),
                ('show_district_filter', models.BooleanField(default=False, verbose_name='إظهار فلتر المديرية')),
                ('items_per_page', models.IntegerField(default=9, verbose_name='عدد العناصر في الصفحة')),
                ('default_view_style', models.CharField(choices=[('grid', 'شبكة'), ('list', 'قائمة')], default='grid', max_length=20, verbose_name='نمط العرض الافتراضي')),
            ],
            options={
                'verbose_name': 'إعدادات صفحة القوائم',
                'verbose_name_plural': 'إعدادات صفحات القوائم',
            },
        ),
    ]
