# Generated by Django 4.2.27 on 2026-01-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_listingconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingconfiguration',
            name='show_gallery',
            field=models.BooleanField(default=True, verbose_name='إظهار المعرض'),
        ),
        migrations.AddField(
            model_name='listingconfiguration',
            name='show_reviews',
            field=models.BooleanField(default=True, verbose_name='إظهار التقييمات'),
        ),
        migrations.AddField(
            model_name='listingconfiguration',
            name='show_sidebar',
            field=models.BooleanField(default=True, verbose_name='إظهار الشريط الجانبي'),
        ),
        migrations.AddField(
            model_name='listingconfiguration',
            name='show_similar_places',
            field=models.BooleanField(default=True, verbose_name='إظهار أماكن مشابهة'),
        ),
        migrations.AddField(
            model_name='listingconfiguration',
            name='show_weather_widget',
            field=models.BooleanField(default=True, verbose_name='إظهار حالة الطقس'),
        ),
        migrations.AlterField(
            model_name='listingconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='صورة افتراضية للمكان', null=True, upload_to='pages/hero/', verbose_name='صورة البانر'),
        ),
        migrations.AlterField(
            model_name='listingconfiguration',
            name='hero_title',
            field=models.CharField(default='استكشف الأماكن', help_text='يستخدم كعنوان افتراضي إذا لم يكن للمكان صورة', max_length=200, verbose_name='عنوان البانر'),
        ),
        migrations.AlterField(
            model_name='listingconfiguration',
            name='page_name',
            field=models.CharField(choices=[('place_list', 'دليل الأماكن (Place List)'), ('nature_list', 'الطبيعة (Nature)'), ('investment_list', 'الاستثمار (Investment)'), ('events_list', 'المناسبات (Events)'), ('place_detail', 'تفاصيل المكان (Place Detail)')], max_length=50, unique=True, verbose_name='الصفحة'),
        ),
    ]
