# Generated by Django 4.2.27 on 2026-01-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_listingconfiguration_show_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='enable_reviews, show_weather, etc.', max_length=100, unique=True)),
                ('label', models.CharField(default='', max_length=200, verbose_name='اسم الميزة')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='مفعل')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ميزة (Feature Toggle)',
                'verbose_name_plural': 'ميزات النظام',
            },
        ),
        migrations.CreateModel(
            name='PlaceDetailBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('hero', 'Hero Section - العرض الرئيسي'), ('gallery', 'Image Gallery - معرض الصور'), ('overview', 'Overview - نظرة عامة'), ('services', 'Services/Units - الوحدات والخدمات'), ('map', 'Map - الخريطة'), ('contact', 'Contact Info - معلومات التواصل'), ('reviews', 'Reviews - التقييمات'), ('ad_banner', 'Ad Banner - إعلان عرضي')], max_length=30, verbose_name='نوع القسم')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان القسم')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_visible', models.BooleanField(default=True, verbose_name='ظاهر')),
                ('custom_class', models.CharField(blank=True, max_length=100, verbose_name='CSS Class مخصص')),
            ],
            options={
                'verbose_name': 'قسم تفاصيل المكان',
                'verbose_name_plural': 'أقسام تفاصيل المكان',
                'ordering': ['order'],
            },
        ),
    ]
