# Generated by Django 4.2.27 on 2026-01-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_featuretoggle_placedetailblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_posts', models.BooleanField(default=False, verbose_name='موافقة تلقائية على المنشورات')),
                ('auto_approve_comments', models.BooleanField(default=False, verbose_name='موافقة تلقائية على التعليقات')),
                ('max_post_length', models.IntegerField(default=500, verbose_name='الحد الأقصى لطول المنشور')),
                ('max_comment_length', models.IntegerField(default=300, verbose_name='الحد الأقصى لطول التعليق')),
            ],
            options={
                'verbose_name': 'إعدادات المجتمع',
                'verbose_name_plural': 'إعدادات المجتمع',
            },
        ),
    ]
