# Generated by Django 4.2.27 on 2026-01-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_communitysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.IntegerField(default=30, verbose_name='مدة الاحتفاظ (أيام)')),
                ('allow_mark_all', models.BooleanField(default=True, verbose_name='السماح بتحديد الكل كمقروء')),
                ('allow_delete', models.BooleanField(default=False, verbose_name='السماح بحذف الإشعارات')),
            ],
            options={
                'verbose_name': 'إعدادات الإشعارات',
                'verbose_name_plural': 'إعدادات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='comment, like, system, etc.', max_length=50, unique=True)),
                ('label', models.CharField(max_length=100, verbose_name='اسم النوع')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='مفعل')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'نوع إشعار',
                'verbose_name_plural': 'أنواع الإشعارات',
                'ordering': ['order'],
            },
        ),
    ]
