# Generated by Django 4.2.27 on 2026-01-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_notificationsetting_notificationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخطوة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'خطوة المعالج',
                'verbose_name_plural': 'خطوات المعالج',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WizardField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200, verbose_name='تسمية الحقل')),
                ('is_required_on_submit', models.BooleanField(default=False, verbose_name='إلزامي عند الإرسال')),
                ('is_visible', models.BooleanField(default=True, verbose_name='ظاهر')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='management.wizardstep')),
            ],
            options={
                'verbose_name': 'حقل المعالج',
                'verbose_name_plural': 'حقول المعالج',
            },
        ),
    ]
