# Generated by Django 4.2.27 on 2026-01-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_add_ui_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='heroslide',
            name='hero_act_ord_idx',
        ),
        migrations.RemoveIndex(
            model_name='homepagesection',
            name='homesec_vis_ord_idx',
        ),
        migrations.RemoveIndex(
            model_name='menu',
            name='menu_loc_act_ord_idx',
        ),
        migrations.RemoveIndex(
            model_name='sidebarlink',
            name='wlink_wid_act_ord_idx',
        ),
        migrations.RemoveIndex(
            model_name='sidebarwidget',
            name='widget_vis_ord_idx',
        ),
        migrations.RemoveIndex(
            model_name='sociallink',
            name='social_act_ord_idx',
        ),
    ]
