# Generated by Django 4.2.27 on 2026-01-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_siteconfiguration_hero_image_and_more'),
        ('management', '0039_remove_heroslide_hero_act_ord_idx_and_more'),
    ]

    operations = [
    ]
