# Generated by Django 4.2.27 on 2026-01-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_merge_20260119_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adinteraction',
            name='ad',
        ),
        migrations.DeleteModel(
            name='BentoItem',
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
        migrations.DeleteModel(
            name='GuideCard',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.DeleteModel(
            name='PublicEmergencyNumber',
        ),
        migrations.DeleteModel(
            name='QuickAccessItem',
        ),
        migrations.DeleteModel(
            name='SidebarItem',
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
        migrations.DeleteModel(
            name='StaticPage',
        ),
        migrations.DeleteModel(
            name='AdInteraction',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
