# Generated by Django 4.2.27 on 2026-01-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_remove_adinteraction_ad_delete_bentoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('banner', 'بانر رئيسي (Homepage)'), ('sidebar', 'شريط جانبي (Sidebar)'), ('navbar', 'شريط علوي (Navbar)')], default='banner', max_length=20, verbose_name='مكان الإعلان'),
        ),
    ]
