# Generated by Django 4.2.27 on 2026-01-25 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_advertisement_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='management.advertisement')),
            ],
            options={
                'verbose_name': 'إحصائيات الإعلان اليومية',
                'verbose_name_plural': 'إحصائيات الإعلانات اليومية',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['advertisement', 'date'], name='management__adverti_c86a70_idx')],
                'unique_together': {('advertisement', 'date')},
            },
        ),
    ]
