# Generated by Django 4.2.27 on 2026-01-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_addailystats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileAuditLog',
        ),
    ]
