# Generated by Django 4.2.27 on 2026-02-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_delete_fileauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheralert',
            name='severity',
            field=models.CharField(choices=[('YELLOW', 'تنبيه أصفر (خفيف)'), ('ORANGE', 'تنبيه برتقالي (متوسط)'), ('RED', 'تنبيه أحمر (خطر)')], max_length=20),
        ),
    ]
