# Generated by Django 4.2.27 on 2026-02-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_systemsetting_alter_notificationsetting_allow_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/banners/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
