# Generated by Codex on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_alter_advertisement_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='target_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط التحويل (اختياري)'),
        ),
    ]
