# Generated by Django 4.2.27 on 2026-02-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_advertisement_target_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status'], name='management__status_836348_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['placement'], name='management__placeme_a7bbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['start_date'], name='management__start_d_95df89_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['end_date'], name='management__end_dat_24a9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'placement', 'start_date', 'end_date'], name='management__status_163f52_idx'),
        ),
    ]
