# Generated by Django 4.2.27 on 2026-02-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_add_ad_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='featuretoggle',
            index=models.Index(fields=['key'], name='management__key_b248af_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['location', 'is_active', 'order'], name='management__locatio_72d316_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['is_public'], name='management__is_publ_f0b216_idx'),
        ),
    ]
