# Generated by Django 4.2.27 on 2025-12-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_review_is_hidden'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
