# Generated by Django 4.2.27 on 2025-12-29 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0006_establishment_commercial_registry_image_and_more'),
        ('interactions', '0005_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreply',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interactions.review'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'place')},
        ),
    ]
