# Generated by Django 4.2.27 on 2025-12-29 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0006_alter_reviewreply_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='رابط الإجراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='', verbose_name='الرسالة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('partner_approved', 'تم اعتماد حسابك كشريك'), ('partner_rejected', 'تم رفض طلب الشراكة'), ('partner_needs_info', 'مطلوب معلومات إضافية'), ('establishment_approved', 'تم قبول المنشأة'), ('establishment_rejected', 'تم رفض المنشأة'), ('establishment_suspended', 'تم إيقاف المنشأة'), ('establishment_reactivated', 'تم إعادة تفعيل المنشأة'), ('ad_approved', 'تم قبول الإعلان'), ('ad_rejected', 'تم رفض الإعلان'), ('ad_payment_needed', 'مطلوب رفع سند الدفع'), ('ad_expiring_soon', 'الإعلان قارب على الانتهاء'), ('ad_expired', 'انتهى الإعلان'), ('new_review', 'تعليق جديد على منشأتك'), ('new_report_on_establishment', 'بلاغ جديد على منشأتك'), ('new_partner_registration', 'تسجيل شريك جديد'), ('partner_upgrade_request', 'طلب ترقية حساب لشريك'), ('new_establishment_request', 'طلب منشأة جديدة'), ('establishment_update_request', 'طلب تحديث منشأة'), ('new_ad_request', 'طلب إعلان جديد'), ('review_objection', 'اعتراض على مراجعة'), ('new_user_report', 'بلاغ جديد من مستخدم'), ('review_reply', 'رد على تعليقك'), ('report_update', 'تحديث على بلاغك'), ('report_resolved', 'تم حل بلاغك'), ('report_rejected', 'تم رفض بلاغك'), ('favorite_suspended', 'تم إيقاف منشأة محفوظة'), ('favorite_reactivated', 'تم إعادة تفعيل منشأة محفوظة'), ('favorite_new_offer', 'عرض جديد على منشأة محفوظة'), ('general', 'إشعار عام')], default='general', max_length=50, verbose_name='نوع الإشعار'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='مقروء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='إشعار جديد', max_length=200, verbose_name='العنوان'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='interaction_recipie_0c9612_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='interaction_recipie_09a5bb_idx'),
        ),
    ]
