# Generated by Django 4.2.27 on 2025-12-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_placecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interactions.placecomment'),
        ),
    ]
