# Generated by Django 4.2.27 on 2025-12-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0009_placecomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='place',
        ),
        migrations.AddField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='report',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
