# Generated by Django 4.2.27 on 2025-12-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0010_remove_report_place_report_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin this review to the top'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Official reply from management'),
        ),
    ]
