# Generated by Django 4.2.27 on 2026-01-01 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0011_review_is_pinned_reviewreply_is_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_all', models.BooleanField(default=True, verbose_name='تفعيل جميع الإشعارات')),
                ('enable_push', models.BooleanField(default=True, verbose_name='إشعارات الدفع')),
                ('enable_email', models.BooleanField(default=False, verbose_name='إشعارات البريد الإلكتروني')),
                ('enable_sms', models.BooleanField(default=False, verbose_name='إشعارات الرسائل النصية')),
                ('disabled_categories', models.JSONField(blank=True, default=dict, help_text='قائمة فئات الإشعارات المعطلة', verbose_name='الفئات المعطلة')),
                ('disabled_types', models.JSONField(blank=True, default=list, help_text='قائمة أنواع الإشعارات المعطلة', verbose_name='الأنواع المعطلة')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='تفعيل ساعات الهدوء')),
                ('quiet_start', models.TimeField(blank=True, null=True, verbose_name='بداية ساعات الهدوء')),
                ('quiet_end', models.TimeField(blank=True, null=True, verbose_name='نهاية ساعات الهدوء')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تفضيلات الإشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
            },
        ),
    ]
