# Generated by Django 4.2.27 on 2026-01-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0013_moderation_engine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='review',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='last_warning_reason',
            field=models.TextField(blank=True, verbose_name='سبب آخر تحذير'),
        ),
        migrations.AddField(
            model_name='review',
            name='original_comment',
            field=models.TextField(blank=True, help_text='النص الأصلي قبل التعديل'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'منشور'), ('hidden', 'مخفي'), ('rejected', 'مرفوض')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='warning_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد التحذيرات'),
        ),
    ]
