# Generated by Django 4.2.27 on 2026-01-02 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0014_enhance_review_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'بلاغ', 'verbose_name_plural': 'البلاغات'},
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='مُسند إلى'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='report',
            name='resolution_note',
            field=models.TextField(blank=True, verbose_name='ملاحظات الحل'),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('INACCURATE', 'معلومات غير دقيقة'), ('SPAM', 'محتوى مزعج'), ('INAPPROPRIATE', 'محتوى غير لائق'), ('SAFETY', 'مخاطر أمنية'), ('COPYRIGHT', 'انتهاك حقوق ملكية'), ('OTHER', 'أخرى')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('NEW', 'جديد'), ('IN_PROGRESS', 'قيد المعالجة'), ('PENDING_INFO', 'بانتظار معلومات'), ('RESOLVED', 'تم الحل'), ('REJECTED', 'مرفوض')], default='NEW', max_length=20),
        ),
    ]
