# Generated by Django 4.2.27 on 2026-01-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0015_enhance_report_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='expected_resolution_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل المتوقع (SLA)'),
        ),
    ]
