# Generated by Django 4.2.27 on 2026-01-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0017_itinerary_remove_reviewreply_is_official_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='interaction_user_id_f4027b_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['place'], name='interaction_place_i_2453d8_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['place', '-created_at'], name='interaction_place_i_6643e1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='interaction_user_id_d08eee_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='interaction_status_410ba8_idx'),
        ),
    ]
