# Generated by Django 4.2.27 on 2026-01-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0018_favorite_interaction_user_id_f4027b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='disabled_categories',
            field=models.JSONField(blank=True, default=dict, verbose_name='الفئات المعطلة'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='disabled_types',
            field=models.JSONField(blank=True, default=list, verbose_name='الأنواع المعطلة'),
        ),
    ]
