# Generated by Django Schema Hardening - 2026-01-13
# interactions/migrations/0020_schema_hardening.py

from django.db import migrations, models


def clean_review_data(apps, schema_editor):
    """Clean invalid review ratings."""
    Review = apps.get_model('interactions', 'Review')
    Review.objects.filter(rating__lt=1).update(rating=1)
    Review.objects.filter(rating__gt=5).update(rating=5)


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0019_alter_notificationpreference_disabled_categories_and_more'),
    ]

    operations = [
        # 1. Clean data first
        migrations.RunPython(clean_review_data, migrations.RunPython.noop),
        
        # 2. Add constraints to Review
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(
                check=models.Q(rating__gte=1, rating__lte=5),
                name='review_rating_range'
            ),
        ),
        
        # 3. Add indexes for GenericForeignKey lookups
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='notif_gfk_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='report_gfk_idx'),
        ),
        
        # 4. Add indexes for common Report queries
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='report_status_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['assigned_to', 'status'], name='report_assigned_idx'),
        ),
        
        # 5. Add indexes for Review queries
        # Index removed because 'status' field causes KeyError
        # migrations.AddIndex(
        #     model_name='review',
        #     index=models.Index(fields=['place', 'status', 'is_hidden'], name='review_place_status_idx'),
        # ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='review_user_date_idx'),
        ),
    ]
