# Generated by Django 4.2.27 on 2026-01-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0019_alter_notificationpreference_disabled_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('partner_approved', 'تم اعتماد حسابك كشريك'), ('partner_rejected', 'تم رفض طلب الشراكة'), ('partner_needs_info', 'مطلوب معلومات إضافية'), ('establishment_approved', 'تم قبول المنشأة'), ('establishment_rejected', 'تم رفض المنشأة'), ('establishment_suspended', 'تم إيقاف المنشأة'), ('establishment_reactivated', 'تم إعادة تفعيل المنشأة'), ('ad_approved', 'تم قبول الإعلان'), ('ad_rejected', 'تم رفض الإعلان'), ('ad_payment_needed', 'مطلوب رفع سند الدفع'), ('ad_expiring_soon', 'الإعلان قارب على الانتهاء'), ('ad_expired', 'انتهى الإعلان'), ('new_review', 'تعليق جديد على منشأتك'), ('new_report_on_establishment', 'بلاغ جديد على منشأتك'), ('pending_change_requested', 'طلب تغيير معلق'), ('pending_change_approved', 'تمت الموافقة على التغيير'), ('pending_change_rejected', 'تم رفض التغيير'), ('partner_field_update', 'تحديث حقل المنشأة'), ('new_partner_registration', 'تسجيل شريك جديد'), ('partner_upgrade_request', 'طلب ترقية حساب لشريك'), ('new_establishment_request', 'طلب منشأة جديدة'), ('establishment_update_request', 'طلب تحديث منشأة'), ('new_ad_request', 'طلب إعلان جديد'), ('review_objection', 'اعتراض على مراجعة'), ('new_user_report', 'بلاغ جديد من مستخدم'), ('review_reply', 'رد على تعليقك'), ('report_update', 'تحديث على بلاغك'), ('report_resolved', 'تم حل بلاغك'), ('report_rejected', 'تم رفض بلاغك'), ('favorite_suspended', 'تم إيقاف منشأة محفوظة'), ('favorite_reactivated', 'تم إعادة تفعيل منشأة محفوظة'), ('favorite_new_offer', 'عرض جديد على منشأة محفوظة'), ('general', 'إشعار عام')], default='general', max_length=50, verbose_name='نوع الإشعار'),
        ),
    ]
