# Generated by Django 4.2.27 on 2026-01-15 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0020_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=100, unique=True, verbose_name='كلمة محظورة')),
                ('severity', models.CharField(choices=[('WARNING', 'تحذير'), ('BLOCK', 'حظر')], default='WARNING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'كلمة محظورة',
                'verbose_name_plural': 'كلمات محظورة',
            },
        ),
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('severity', models.CharField(max_length=20)),
                ('matched_terms', models.JSONField(default=list)),
                ('action_taken', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='reviewreply',
            name='replier',
        ),
        migrations.RemoveField(
            model_name='reviewreply',
            name='review',
        ),
        migrations.AlterModelOptions(
            name='placecomment',
            options={'ordering': ['created_at'], 'verbose_name': 'تعليق', 'verbose_name_plural': 'تعليقات'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقييم', 'verbose_name_plural': 'تقييمات'},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='interaction_user_id_d08eee_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='interaction_status_410ba8_idx',
        ),
        migrations.RenameField(
            model_name='placecomment',
            old_name='is_hidden',
            new_name='is_edited',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='review',
            name='last_warning_reason',
        ),
        migrations.RemoveField(
            model_name='review',
            name='original_comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.RemoveField(
            model_name='review',
            name='warning_count',
        ),
        migrations.AddField(
            model_name='placecomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placecomment',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placecomment',
            name='hidden_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placecomment',
            name='moderation_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='placecomment',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interactions.review'),
        ),
        migrations.AddField(
            model_name='placecomment',
            name='visibility_state',
            field=models.CharField(choices=[('visible', 'Visible'), ('partner_hidden', 'Hidden by Partner'), ('admin_hidden', 'Hidden by Admin')], default='visible', max_length=20),
        ),
        migrations.AlterField(
            model_name='placecomment',
            name='content',
            field=models.TextField(verbose_name='نص التعليق'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='نص التقييم'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='التقييم'),
        ),
        migrations.AddIndex(
            model_name='placecomment',
            index=models.Index(fields=['place', 'created_at'], name='interaction_place_i_6a3250_idx'),
        ),
        migrations.AddIndex(
            model_name='placecomment',
            index=models.Index(fields=['place', 'visibility_state', 'created_at'], name='interaction_place_i_bb2e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='placecomment',
            index=models.Index(fields=['parent', 'created_at'], name='interaction_parent__076d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='interaction_rating_a6492a_idx'),
        ),
        migrations.DeleteModel(
            name='ReviewReply',
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
