# Generated by Django 4.2.27 on 2026-01-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0020_schema_hardening'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_rating_range',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_gfk_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='report_gfk_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='report_status_prio_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='report_assigned_idx',
        ),
        # Index removal skipped because creation was skipped in 0020
        # migrations.RemoveIndex(
        #     model_name='review',
        #     name='review_place_status_idx',
        # ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_user_date_idx',
        ),
    ]
