# Generated by Django 4.2.27 on 2026-01-16 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0021_bannedword_moderationevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], default='push', max_length=20, verbose_name='Channel')),
                ('provider', models.CharField(choices=[('onesignal', 'OneSignal'), ('fcm', 'Firebase Cloud Messaging'), ('email', 'Email'), ('none', 'None')], default='fcm', max_length=20, verbose_name='Provider')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('dead', 'Dead Letter')], db_index=True, default='queued', max_length=20, verbose_name='Status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Attempts')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='Max Attempts')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Last Error')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Scheduled At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_outbox', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification Outbox',
                'verbose_name_plural': 'Notification Outbox',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='interaction_status_9a2dd9_idx'), models.Index(fields=['recipient', 'status'], name='interaction_recipie_98a7ef_idx')],
            },
        ),
    ]
