# Generated by Django 4.2.27 on 2026-01-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0023_notification_event_type_notification_metadata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannedWord',
        ),
        migrations.RemoveField(
            model_name='moderationqueueitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='moderationqueueitem',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='moderationrule',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ModerationEvent',
        ),
        migrations.DeleteModel(
            name='ModerationQueueItem',
        ),
        migrations.DeleteModel(
            name='ModerationRule',
        ),
    ]
