# Generated by ChatGPT on 2026-01-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0024_delete_bannedword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='visibility_state',
            field=models.CharField(
                choices=[
                    ('visible', 'Visible'),
                    ('partner_hidden', 'Hidden by Partner'),
                    ('admin_hidden', 'Hidden by Admin'),
                ],
                default='visible',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='review',
            name='hidden_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='hidden_reviews',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='review',
            name='hidden_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['place', 'visibility_state', 'created_at'], name='interactions_review_vis_idx'),
        ),
    ]
