# Generated by Django 4.2.27 on 2026-01-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0021_remove_review_review_rating_range_and_more'),
        ('interactions', '0025_review_visibility_state'),
    ]

    operations = [
    ]
