# Generated by Django 4.2.27 on 2026-01-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0026_merge_20260119_2321'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='interaction_place_i_6643e1_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='interaction_place_i_398ce4_idx',
            old_name='interactions_review_vis_idx',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['place', 'created_at'], name='interaction_place_i_7a8c9a_idx'),
        ),
    ]
