# Generated by Django 4.2.27 on 2026-01-21 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0029_add_license_registration_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0027_remove_review_interaction_place_i_6643e1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='places.establishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'متابعة',
                'verbose_name_plural': 'المتابعات',
                'indexes': [models.Index(fields=['user', '-created_at'], name='interaction_user_id_41bedc_idx'), models.Index(fields=['establishment'], name='interaction_establi_df8fb2_idx')],
                'unique_together': {('user', 'establishment')},
            },
        ),
    ]
