# Generated by Django 4.2.27 on 2026-01-26 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0029_notification_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التنبيه')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('alert_type', models.CharField(choices=[('WEATHER_ALERT', 'تنبيه طقس'), ('SYSTEM_ALERT', 'تنبيه نظام'), ('STAFF_ALERT', 'تنبيه إداري')], default='SYSTEM_ALERT', max_length=50, verbose_name='نوع التنبيه')),
                ('target_audience', models.CharField(choices=[('all', 'الجميع (بث عام)'), ('partners', 'الشركاء فقط'), ('staff', 'المشرفين فقط')], default='all', max_length=50, verbose_name='الجمهور المستهدف')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'تنبيه جماعي / طقس',
                'verbose_name_plural': 'التنبيهات الجماعية',
                'ordering': ['-created_at'],
            },
        ),
    ]
