# Generated by Django 4.2.27 on 2026-02-12 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0033_specialoffer'),
        ('interactions', '0031_livesharesession_livelocationping'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'view'), ('click', 'click'), ('save', 'save'), ('share', 'share'), ('rate', 'rate'), ('search', 'search'), ('open_map', 'open_map'), ('call', 'call'), ('book', 'book'), ('report', 'report')], max_length=20)),
                ('action_value', models.FloatField(blank=True, null=True)),
                ('query_text', models.TextField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=120, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['place', 'created_at'], name='interaction_place_i_64ed2e_idx'), models.Index(fields=['user', 'created_at'], name='interaction_user_id_8e892b_idx'), models.Index(fields=['action', 'created_at'], name='interaction_action_c3aa48_idx')],
            },
        ),
    ]
