# Generated by Django 4.2.27 on 2026-02-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0034_alter_eventlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.CharField(choices=[('view', 'view'), ('click', 'click'), ('save', 'save'), ('share', 'share'), ('rate', 'rate'), ('search', 'search'), ('open_map', 'open_map'), ('call', 'call'), ('book', 'book'), ('report', 'report'), ('dwell', 'dwell'), ('scroll', 'scroll'), ('nearby_click', 'nearby_click')], max_length=20),
        ),
    ]
