# Generated by Django 4.2.27 on 2026-02-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0035_alter_eventlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/images/', verbose_name='صورة'),
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
    ]
