# Generated by Django 4.2.27 on 2026-01-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UIComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العنصر')),
                ('slug', models.SlugField(unique=True)),
                ('template_path', models.CharField(help_text='e.g., components/molecules/weather_widget.html', max_length=255, verbose_name='مسار القالب')),
                ('default_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات افتراضية')),
            ],
        ),
        migrations.CreateModel(
            name='UIZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنطقة')),
                ('slug', models.SlugField(help_text='e.g., sidebar_right, homepage_main', unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_visible', models.BooleanField(default=True, verbose_name='طاهر')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.uicomponent')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cms.uizone')),
            ],
            options={
                'verbose_name': 'مكون المنطقة',
                'verbose_name_plural': 'مكونات المنطقة',
                'ordering': ['order'],
            },
        ),
    ]
