# Generated by ChatGPT on 2026-01-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zonecomponent',
            name='stage',
            field=models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور')], db_index=True, default='published', max_length=16, verbose_name='المرحلة'),
        ),
        migrations.AddField(
            model_name='zonecomponent',
            name='data_override',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات مخصصة'),
        ),
        migrations.AddField(
            model_name='zonecomponent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='zonecomponent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.CreateModel(
            name='UIRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='publish', max_length=32, verbose_name='الإجراء')),
                ('from_stage', models.CharField(blank=True, max_length=16, verbose_name='من مرحلة')),
                ('to_stage', models.CharField(blank=True, max_length=16, verbose_name='إلى مرحلة')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='اللقطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cms.uizone')),
            ],
            options={
                'verbose_name': 'نسخة واجهة',
                'verbose_name_plural': 'نسخ الواجهة',
                'ordering': ['-created_at'],
            },
        ),
    ]
