# Generated by ChatGPT on 2026-01-14

from django.db import migrations


def seed_layout(apps, schema_editor):
    UIZone = apps.get_model('cms', 'UIZone')
    UIComponent = apps.get_model('cms', 'UIComponent')
    ZoneComponent = apps.get_model('cms', 'ZoneComponent')

    # Header zone + component
    header_zone, _ = UIZone.objects.get_or_create(
        slug='header_nav',
        defaults={'name': 'الهيدر / شريط التنقل', 'description': 'منطقة شريط التنقل العلوي'}
    )
    header_comp, _ = UIComponent.objects.get_or_create(
        slug='header_navbar',
        defaults={
            'name': 'شريط التنقل (Navbar)',
            'template_path': 'components/layout/header_navbar.html',
            'default_data': {},
        }
    )

    # Footer zone + component
    footer_zone, _ = UIZone.objects.get_or_create(
        slug='footer_main',
        defaults={'name': 'الفوتر', 'description': 'منطقة الفوتر الرئيسية'}
    )
    footer_comp, _ = UIComponent.objects.get_or_create(
        slug='footer_main',
        defaults={
            'name': 'الفوتر الرئيسي',
            'template_path': 'components/layout/footer_main.html',
            'default_data': {},
        }
    )

    # Ensure published instances exist
    ZoneComponent.objects.get_or_create(
        zone=header_zone, component=header_comp,
        stage='published',
        defaults={'order': 1, 'is_visible': True, 'data_override': {}}
    )
    ZoneComponent.objects.get_or_create(
        zone=footer_zone, component=footer_comp,
        stage='published',
        defaults={'order': 1, 'is_visible': True, 'data_override': {}}
    )


def unseed_layout(apps, schema_editor):
    # Keep objects to avoid destructive rollbacks in production
    return


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_zonecomponent_stage_and_revision'),
    ]

    operations = [
        migrations.RunPython(seed_layout, unseed_layout),
    ]
