# Generated by Django 4.2.27 on 2025-12-31 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاستبيان')),
                ('description', models.TextField(blank=True, verbose_name='وصف الاستبيان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استبيان',
                'verbose_name_plural': 'الاستبيانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='نص السؤال')),
                ('question_type', models.CharField(choices=[('rating', 'تقييم (1-5)'), ('text', 'نص حر'), ('choice', 'اختيار من متعدد'), ('yesno', 'نعم/لا')], max_length=20, verbose_name='نوع السؤال')),
                ('choices', models.JSONField(blank=True, default=list, help_text='خيارات السؤال (للاختيار من متعدد)')),
                ('is_required', models.BooleanField(default=True, verbose_name='مطلوب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'سؤال استبيان',
                'verbose_name_plural': 'أسئلة الاستبيان',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(default=dict, verbose_name='الإجابات')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رد استبيان',
                'verbose_name_plural': 'ردود الاستبيانات',
                'unique_together': {('survey', 'user')},
            },
        ),
    ]
