# Generated by Django 4.2.27 on 2026-02-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('rating', 'تقييم (1-5)'), ('text', 'نص حر'), ('choice', 'اختيار من متعدد (راديو)'), ('checkbox', 'اختيارات متعددة (صندوق اختيار)'), ('select', 'قائمة منسدلة'), ('number', 'رقم'), ('date', 'تاريخ'), ('yesno', 'نعم/لا')], max_length=20, verbose_name='نوع السؤال'),
        ),
    ]
