# Generated by Django 4.2.27 on 2026-02-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_surveyquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='max_responses',
            field=models.PositiveIntegerField(blank=True, help_text='سيتم إغلاق الاستبيان تلقائياً عند الوصول لهذا العدد (اتركه فارغاً للاستمرار بلا حدود)', null=True, verbose_name='الحد الأقصى للردود'),
        ),
    ]
