# Generated by Django 4.2.27 on 2026-02-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_max_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='choices',
            field=models.JSONField(blank=True, default=list, help_text='ادخل الخيارات (خيار واحد في كل سطر). سيتم استخدامها في أسئلة الاختيار من متعدد.', verbose_name='الخيارات'),
        ),
    ]
